#!/usr/bin/python
import json
from subprocess import call
import shlex
import os.path

path = "/home/"
kcp_config_file = path + "kcp.json"
ss_config_file = path + "shadowsocks.json"

def init():
    if os.path.isfile(ss_config_file) == False:
        print "ss config file not found!"
        return
    if os.path.isfile(kcp_config_file) == False:
        print "kcp config file not found!"
        return
    
    # generate commands
    ss_command = "ss-server -c " + ss_config_file + "&"
    kcp_command = "server_linux_amd64 -c " + kcp_config_file
    
    # run ssserver
    # TODO
    call(ss_command, shell=True)

    # run kcpserver
    # TODO
    call(shlex.split(kcp_command))

init()